services:
  - type: web
    name: vtu-results-scraper
    runtime: python
    plan: free
    buildCommand: bash build.sh
    startCommand: gunicorn vtu_results_hosted:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: DEVELOPMENT
        value: "True"
      - key: MANUAL_CAPTCHA
        value: "True"
      - key: FORCE_DEMO
        # Set to True if you want to use demo mode
        value: "False" 